name: Deploy TODO App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME_TODO: <твой-докерхаб-юзернейм>/todo-app
      IMAGE_NAME_NGINX: <твой-докерхаб-юзернейм>/todo-nginx

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build todo-app image
      run: docker build -t $IMAGE_NAME_TODO ./todo-app

    - name: Build nginx image
      run: docker build -t $IMAGE_NAME_NGINX ./docker/nginx

    - name: Push todo-app image
      run: docker push $IMAGE_NAME_TODO

    - name: Push nginx image
      run: docker push $IMAGE_NAME_NGINX

    - name: Deploy on server (optional, если есть VPS)
      if: github.ref == 'refs/heads/main'
      run: echo "Deploy stage (можно добавить SSH + docker-compose up)"
